name: My Panda CI
on:
  push:
    branches: [main]

jobs:
  builds:
    runs-on: ubuntu-latest
    name: my build
    steps:
      - name: Send Discord Message
        uses: discord-actions/message@v2
        with:
          webhookUrl: https://discordapp.com/api/webhooks/1316956354786885673/TnLUfOQiSbcjinGjEXP44tQwVosbe8HGv_gviHMyIZYWbWlr4rcTYRDpNk24h2DO7pa5
          message: "helloooo"
          avatar: https://github.com/verina-dinata/discordTest/blob/main/481c2d138445621.621de4428a451.png
          

